builds:
  - id: cloudcored
    main: ./cmd/cloudcored
    binary: cloudcored
    ldflags:
      - -s -w -X github.com/clarkmcc/cloudcore/pkg/version.Version={{.Version}} -X github.com/clarkmcc/cloudcore/pkg/version.Hash={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
#      - windows
      - darwin
      - linux
    goarch:
#      - amd64
      - arm64
#      - arm
    goarm:
#      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
        goarm: 6
      - goos: darwin
        goarch: arm
        goarm: 7
nfpms:
  - id: cloudcored-linux
    package_name: cloudcored
    builds:
      - cloudcored
    vendor: cloudcore
    homepage: https://cloudcore.clarkmccauley.com/
    maintainer: Clark McCauley
    license: MIT
    formats:
      - deb
# todo: Setup systemd service
#    scripts:
#      preinstall: scripts/linux/preinstall.sh
#      postinstall: scripts/linux/postinstall.sh
#      preremove: scripts/linux/preremove.sh
#      postremove: scripts/linux/postremove.sh
# Whether to enable the size reporting or not.
report_sizes: true