builds:
  - id: cloudcored
    main: ./cmd/cloudcored
    binary: cloudcored
    ldflags:
      - -s -w -X github.com/clarkmcc/cloudcore/pkg/version.Version={{.Version}} -X github.com/clarkmcc/cloudcore/pkg/version.Hash={{.Commit}} -X github.com/clarkmcc/cloudcore/pkg/version.GOARM={{.Env.GOARM}}
    env:
      - CGO_ENABLED=0
    targets:
#      - windows_amd64
#      - windows_arm64
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm_5
  - id: cloudcore-server
    main: ./cmd/cloudcore-server
    binary: cloudcore
    ldflags:
      - -s -w -X github.com/clarkmcc/cloudcore/pkg/version.Version={{.Version}} -X github.com/clarkmcc/cloudcore/pkg/version.Hash={{.Commit}}
    env:
      - CGO_ENABLED=0
    targets:
#      - windows_amd64
#      - windows_arm64
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm_5
nfpms:
  - id: cloudcored-linux
    package_name: cloudcored
    builds:
      - cloudcored
    file_name_template: >- 
      {{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}_{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    vendor: cloudcore
    homepage: https://cloudcore.clarkmccauley.com/
    maintainer: Clark McCauley
    license: MIT
    formats:
      - deb
      - apk
      - rpm
    scripts:
      preinstall: scripts/linux/preinstall.sh
# todo: Setup systemd service
#      postinstall: scripts/linux/postinstall.sh
#      preremove: scripts/linux/preremove.sh
#      postremove: scripts/linux/postremove.sh
# Whether to enable the size reporting or not.

dockers:
  # Server
  - id: cloudcore-server
    image_templates:
      - ghcr.io/clarkmcc/cloudcore
    ids:
      - cloudcore-server
    goos: linux
    goarch: amd64
    dockerfile: ./cmd/cloudcore-server/Dockerfile

archives:
  - id: cloudcored-archive
    builds:
      - cloudcored
    wrap_in_directory: false
    name_template: >- 
      {{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}_{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    format: binary

report_sizes: true
