builds:
  - id: cloudcored
    main: ./cmd/cloudcored
    binary: cloudcored
    ldflags:
      - -s -w -X github.com/clarkmcc/cloudcore/pkg/version.Version={{.Version}} -X github.com/clarkmcc/cloudcore/pkg/version.Hash={{.Commit}}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm_5
nfpms:
  - id: cloudcored-linux
    package_name: cloudcored
    builds:
      - cloudcored
    vendor: cloudcore
    homepage: https://cloudcore.clarkmccauley.com/
    maintainer: Clark McCauley
    license: MIT
    formats:
      - deb
    scripts:
      preinstall: scripts/linux/preinstall.sh
# todo: Setup systemd service
#      postinstall: scripts/linux/postinstall.sh
#      preremove: scripts/linux/preremove.sh
#      postremove: scripts/linux/postremove.sh
# Whether to enable the size reporting or not.

dockers:
  # Server
  - id: cloudcore-server
    goos: linux
    goarch: amd64
    dockerfile: ./cmd/cloudcore-server/Dockerfile

report_sizes: true
